### ISSUE TITLE
Auto-certify capability configurable for inbound collection workflow

### ISSUE THREAD

**Issue by awcrosby** [ansible/galaxy_ng#115]
### Use Case
- Default on-prem workflow will match CRC initially
- This capability would allow on-prem customer to change how default workflow behaves
- This config option would apply to entire on-prem system
- When turned on, inbound collections would move from inbound repo, to staging repo, then to final general availability repo with no user or admin interaction.

**Comment by chouseknecht** [comment]
Sub-task of #20
