### ISSUE TITLE
Transition from using certification flag to repo certification workflow

### ISSUE THREAD

**Issue by awcrosby** [ansible/galaxy_ng#120]
Subtask of #20

- [x] Phase-out use of certified flag (Remove from UI @ZitaNemeckova)
- [x] Transition to using new workflow and new certification-dashboard
- [x] Remove v3 CollectionVersion certified flag filter

**Comment by ZitaNemeckova** [comment]
UI part https://github.com/ansible/ansible-hub-ui/pull/188
