### ISSUE TITLE
UI: Add user avatar and toolbar in masthead 

### ISSUE THREAD

**Issue by newswangerd** [ansible/galaxy_ng#13]
We need to update the masthead to include the current user's avatar and optionally a menu for them to access their settings. 

![Screen Shot 2020-02-21 at 1 02 30 PM](https://user-images.githubusercontent.com/6063371/75059197-73ab4880-54aa-11ea-8575-717f6bcd9dfd.png)

**Comment by chouseknecht** [comment]
Subtask of #16

**Comment by ironfroggy** [comment]
@newswangerd  There does not seem to be any avatar. Is that a planned change or a missing feature?
