### ISSUE TITLE
[proposal] Support building and publishing collections server side

### ISSUE THREAD

**Issue by geerlingguy** [ansible/galaxy_ng#133]
### Use Case

Currently the process for releasing new collection versions requires:

  1. A collection maintainer run `ansible-galaxy collection build` to build an artifact.
  2. A collection maintainer run `ansible-galaxy collection publish` to publish it to Galaxy.

There are already some minor annoyances caused by this process, for example:

  - Unwanted files (e.g. anything in the collection maintainer's local checkout that's not explicitly excluded, like a `.DS_Store` file on macOS) can sneak into the artifact (see https://github.com/ansible-collections/kubernetes/issues/29)
  - Each collection maintainer has to either run through the publishing process manually, or automate the process in CI—but the latter option must be set up per collection (and there's no central tool to do this, so it's every collection for itself), and it also means that a single user must upload an access token that's valid for any and all Ansible content on Galaxy that the user's namespaces can access (see https://github.com/ansible/galaxy/issues/2276 and https://github.com/ansible/galaxy/issues/2275).

One alternative that would neatly sidestep these issues would be to allow the option of Galaxy automatically building new versions, e.g. if notified by a CI tool via webhook—just like is currently possible for Galaxy roles.

I know that role _artifacts_ aren't currently hosted by Galaxy, but one of the reasons roles are so prosperous and also can be updated easily and frequently (increasing the appeal of both maintaining and using them), is that all that was required to plug a role into Galaxy was to add something like this to your CI workflow:

```yaml
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
```

If I could do the same thing with collections, and have it set up so that when I tag a `1.2.3`, Galaxy builds and publishes that release artifact, it would mean more consistency, a more standardized build, and better security (since Galaxy would pull the source and build internally).

I believe there's a strong precedent for this, in that many other services do the same (host the artifact build process to ease the burden of pushing up artifacts consistently):

  - Docker Hub automated builds
  - GitHub Actions package builds
  - Ansible Galaxy role notification updates (technically different but the same idea)

### Proposed Solution

Add the ability for a 'webhook' to be notified in Galaxy (similar to the roles webhook):

    https://galaxy.ansible.com/api/v3/notifications/?repo=git://github.com/blah.git&tag=1.2.3

When this webhook is notified, Galaxy looks up the Repository URL, checks that the repository matches a repository for a collection on Galaxy, and builds an artifact for the given release.

### Alternatives

Provide some sort of 'best practices' / automation options for the build process, ideally with many different flavors, e.g. a script that could be used in one of:

  - GitHub Actions
  - Travis CI
  - Azure Pipelines
  - A shell script

### Implementation

N/A

**Comment by newswangerd** [comment]
Moved to issues.redhat.com/
