### ISSUE TITLE
Installer: create primary pulp repository

### ISSUE THREAD

**Issue by ironfroggy** [ansible/galaxy_ng#139]
The installer should handle creating the primary repository. This and other configuration steps probably should be in their own role. It isn't clear where that should live.

- Should create a repository and distribution
- Repository name should be configurable in the install playbook
- The admin user and/or any admin group should be added to it

**Comment by chouseknecht** [comment]
Looks like we need to follow some of these steps: 

https://pulp-ansible.readthedocs.io/en/latest/workflows/collections.html

**Comment by chouseknecht** [comment]
Created an Ansible role to do this, and added to install instructions. [See updated install instructions here](https://github.com/ansible/galaxy_ng/wiki/End-User-Installation). Probably not perfect, but a good first step.
