### ISSUE TITLE
UI standalone login page

### ISSUE THREAD

**Issue by newswangerd** [ansible/galaxy_ng#14]
We currently rely on the cloud.redhat.com login page when a user needs to authenticate. We need to add a custom a login page that can be used in standalone environments where Red Hat cloud services are not available.

The login page will most likely need to support
- enterprise SSO for on prem environments
- basic username/password auth

**Comment by chouseknecht** [comment]
Subtask of #75

**Comment by ironfroggy** [comment]
Implemented by https://github.com/ansible/ansible-hub-ui/pull/131 ?
