### ISSUE TITLE
Importer: configurable path for galaxy-importer.cfg file

### ISSUE THREAD

**Issue by wojtek0806** [ansible/galaxy_ng#148]
### Use Case

In some environments it is not possible or practical to add galaxy-importer.cfg to either the 2 following locations:
```
/etc/galaxy-importer/galaxy-importer.cfg
<code_source>/galaxy_importer/galaxy-importer.cfg
```
### Proposed Solution

A better solution would be to add a 3rd option for a custom directory location provided by the user from CLI when launching the application. 

The entry from the CLI should be taking the highest priority which would be in line with what Ansible does too, so it will go here:

https://github.com/ansible/galaxy-importer/blob/master/galaxy_importer/config.py#L24

and change this function to pull the cfg file from args if present:

https://github.com/ansible/galaxy-importer/blob/master/galaxy_importer/main.py#L36

### Alternatives

I have considered installing from devel repo and placing /galaxy_importer/galaxy-importer.cfg inside the source but the preference is to install using pip

**Comment by chouseknecht** [comment]
For now you can, as you mention, clone the project, install via `pip -e .[dev]`, and add your configuration into the cloned directory.

Ideally, we should add support for environment variable that can be set to point to a config file.

**Comment by awcrosby** [comment]
Moving to `ready-for-QE`, addressed in https://github.com/ansible/galaxy-importer/pull/65
