### ISSUE TITLE
Importer: Add check for max length for urls in metadata

### ISSUE THREAD

**Issue by awcrosby** [ansible/galaxy_ng#162]
Add a 2000 char limit for the URL fields in collection metadata: documentation, homepage, issues, repository

**Comment by pabelanger** [comment]
AH is rejection collections now that have 64+ characters for author field. This isn't the issue it self, however the error is raised to late in the validate process.

Both ansible-galaxy build collection or galaxy-importer tool do not catch this validation, making it almost impossible for CI jobs to validate the galaxy.yml file before uploads to AH.

ErrorDetail(string='Ensure this field has no more than 64 characters.', code='max_length')]

https://4931fc23ada12d28bae0-cfd71c638bec22f63907724a266c8b7a.ssl.cf2.rackcdn.com/a2876f0801e7411331d21ede824755f961e0415d/release/release-ansible-collection-automation-hub/b5a8a91/job-output.html#l1050

**Comment by gundalow** [comment]
What are the thoughts longer term about where validation should go *before* publish?
For example, should `ansible-galaxy build` include all validation that may exist in later steps of the build/publish process for Galaxy & AH?

I'd like to ensure the collection repos are valid without publishing them, ie per PR validation in GitHub.

**Comment by pabelanger** [comment]
> What are the thoughts longer term about where validation should go _before_ publish?
> For example, should `ansible-galaxy build` include all validation that may exist in later steps of the build/publish process for Galaxy & AH?
> 
> I'd like to ensure the collection repos are valid without publishing them, ie per PR validation in GitHub.

Yes, IMO this is what we should do. Any sort of validation or testing, should be done before releasing the artifact to galaxy. We do this today in a CI system as best as possible, but some things are just not exposed into current testing tools.

As you say, pre-release testing should catch all of this, not post-release. As, each failure found in galaxy after the fact, usually results in a new release having to happen.

**Comment by chouseknecht** [comment]
Migrated to Jira: AAH-54
