### ISSUE TITLE
FEAT: Highlight maintenance release trains / versions in AH

### ISSUE THREAD

**Issue by abenokraitis** [ansible/galaxy_ng#166]
### Use Case
Paying Ansible customers will have access to Automation Hub which will have different content than Galaxy. For example, a longer life cycle for a collection. With the current implementation these stable releases will have earlier version numbers and therefore will be buried at the bottom. Also, it isn't clear if a version is part of a longer-life maintenance train.

### Proposed Solution
I'll defer to others for their ideas but something possibly outside of Version or somehow highlight that a version is part of a longer-life maintenance train, as opposed to the latest-and-greatest that's also in Galaxy (also valid).

### Alternatives
- Enhance the existing version field
- Create a new field
- Create a more dynamic field that first asks if you want the latest upstream release or a specific version as part of a maintenance release

### Implementation
Not sure yet, may need some brainstorming

**Comment by chouseknecht** [comment]
This is covered in our backlog and planning documentation. Closing for now. Will re-open in [Jira](https://issues.redhat.com), once it's incorporated into a PRD.
