### ISSUE TITLE
Story: Content Sync

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy_ng#17]
### Use Case

As an AH administrator: 
- From the universe of subscriber content, I want to construct a list of namespaces or namespace.collection(s) to exclude or hide from my private AH.
- On my private AH, I want to use the UI to configure the sync remote, API key, and any other parameters. 
- On my private AH, I want to initiate the sync from the UI.
- In the future, I may want to create multiple blacklists. For example, I might one per private AH instance. Or, perhaps I have multiple repositories in my one private AH and I want to control the content sync’d into each.

### Notes

- The list of what not to download to private AH (i.e., blacklist) will be created upstream, server side
- Build the feature for c.rh.com first. Defer the feature on community until the future of community is decided

### Design

- As an admin, log into AH and create a blacklist of collections. User will blacklist an entire collection, not specific versions. TBD what the actual user experience is and how it manifests in the UI.
- On the backend, create a repository containing all available collection versions minus any collections on the user’s blacklist, and create a distribution that contains the repository. The local AH synch will mirror this repository using the distribution URL.
- As an admin on private AH, manually configure the remote endpoint and credentials.
- As an admin on private AH, initiates a sync.

#### Workflow to support user selecting collections:

- User chooses to add a Collection to the blacklist.
- UI calls a /blacklist endpoint that accepts a Collection ID or a list of Collection IDs. The underlying viewset will offer list, post, and put operations to manipulate a Blacklist model.
- The API will:
    - Update new data model to track user’s request to exclude the collection, which is a many-to-many between user and collection. Think of collection as a ‘stream of versions’, thus we’re tracking the request at the collection level vs the collection version level.
    - Does the user already have a sync repository? If not, create one.
    - If creating a repository:
        - Create a repository (https://pulp-ansible.readthedocs.io/en/latest/restapi.html#operation/repositories_ansible_ansible_list)
       - Associate the repository with the user
       - Create a distribution (https://pulp-ansible.readthedocs.io/en/latest/restapi.html#operation/distributions_ansible_ansible_list)
       - Associate the distribution URL with the user. Need to be able to surface this URL in the UI, making it available for copy-paste to private AH.
      - Add collection versions to the repository using the Pulp modify API. Ideally we need a ‘Copy’ API in pulp_ansible. (Brian will create an issue and deliver this.)

Tasks
- [x] Model/design for upstream / automation-hub
  - [x] Model object design for Blacklist, SyncList, SyncCollection, SyncNamespace (and/or pulp Remote style objects)
  - [x] Model object design for any UI objects needed 
~~- [ ] Model/design for "downstream" (private) galaxy_ng server~~
  ~~- [ ] Model object design~~ 
      ~~- [ ] pulp CollectionRemote~~
      ~~- [ ] pulp NamespaceRemote~~
      ~~- [ ] downstream Blacklist if needed (cache based on upstream Blacklist?)~~
- [x] Design upstream / automation-hub API endpoints
  - [x] Sketch out in openapi for review
  - [x] endpoints
    - [x] /blacklist
- [x] Design downstream / private API endpoints
  - [x]  Sketch out in openapi for review
  - [x] endpoints
    - [x] UI stuff for setting up remotes if needed
    - [x] UI stuff for initiating sync if needed  (could also use pulp api directly)
- [x] upstream / automation-hub tasks
  - [x] pulp task for creating repos if sync/blacklist are added
  - [x] pulp task for updating upstream "syncable" repos when content is promoted to "golden" repo (possibly based on bmbouters examples for scale test) [ likely this task that will take the most effort/time]

**Comment by chouseknecht** [comment]
![image](https://user-images.githubusercontent.com/1282865/76839888-b263c280-680c-11ea-938d-86cf142d7235.png)

**Comment by chouseknecht** [comment]
![image](https://user-images.githubusercontent.com/1282865/76839937-c5769280-680c-11ea-94d3-a5f698e95ad3.png)

**Comment by alikins** [comment]
@chouseknecht @cutwater @romanblanco  In the API for creating SyncLists, how should the API
reference the Repository?


A pulp Ansible Repository serialized to json looks like

``` json
        {
            "description": null,
            "latest_version_href": "/pulp/api/v3/repositories/ansible/ansible/20ab43ad-24ee-4868-8127-88a9ab590317/versions/3/",
            "name": "automation-hub",
            "pulp_created": "2020-03-12T15:56:19.071000Z",
            "pulp_href": "/pulp/api/v3/repositories/ansible/ansible/20ab43ad-24ee-4868-8127-88a9ab590317/",
            "versions_href": "/pulp/api/v3/repositories/ansible/ansible/20ab43ad-24ee-4868-8127-88a9ab590317/versions/"
        }
```

Also see https://pulp-ansible.readthedocs.io/en/latest/restapi.html#operation/repositories_ansible_ansible_list  200 response schema

pulp itself always uses the 'pulp_href' value when referencing a particular AnsibleRespository.

Should the API for creating a synclist expect SyncList's 'repository' field to be in the form of
a pulp_href?  

Should it be the Respository name (not sure if unique)? 

Should it be just the uuid part of the pulp_href?  . Current implementation in https://github.com/ansible/galaxy_ng/pull/68 does this. Mostly because the db pk is
just the uuid part (ie, '20ab43ad-24ee-4868-8127-88a9ab590317' from the example above).

**Comment by alikins** [comment]
> 
> - [ ] Model/design for "downstream" (private) galaxy_ng server
>   - [ ] Model object design 
>       - [ ] pulp CollectionRemote
>       - [ ] pulp NamespaceRemote
>       - [ ] downstream Blacklist if needed (cache based on upstream Blacklist?)

Some/most of this related to pulp_ansible:
https://pulp.plan.io/issues/6540
https://github.com/pulp/pulp_ansible/pull/326

**Comment by alikins** [comment]
https://pulp.plan.io/issues/6197 isn't necessarily a requirement for #17, especially if the ' '/move/' endpoint is added to galaxy_ng.  But it would be useful.
