### ISSUE TITLE
API/AUTH: Allow tower to programatically generate auth tokens

### ISSUE THREAD

**Issue by alikins** [ansible/galaxy_ng#187]
Related: #171

"Obtain an API token programmatically" -

Is the Token in question the SSO/keycloak like is used in cloud.redhat.com for ansible-galaxy authentication via it's server 'auth_url' and 'token'? This can be done 'programmaticly' in the sense that Tower can get a SSO token from the 'auth_url' if needed.
and/or

The django session token as provided at the /_ui/auth/{login,token} endpoints. This should be able to be done programmatically, but would required use of credentials stored in tower

and/or

Other.

**Comment by chouseknecht** [comment]
- The `token` is purely a DRF token only
- The endpoint to interact with tokens should only be available in local AH, not in the cloud.
