### ISSUE TITLE
UI: Create page for managing user groups

### ISSUE THREAD

**Issue by newswangerd** [ansible/galaxy_ng#191]
Right now our user groups are created and managed by Red Hat SSO. In order to run automation hub in standalone mode we need a page for creating and managing groups.

This should allow an admin to log in and
- View all the groups
- Add and remove users from a group
- See which namespaces a group can upload to
- Assign permissions to groups

**Comment by chouseknecht** [comment]
Subtask of #16

**Comment by chouseknecht** [comment]
Subtask of #21
