### ISSUE TITLE
Document auto-certify

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy_ng#207]
Subtask of #170 

- [x] Update the sample playbook in README and wiki to include `PULP_GALAXY_REQUIRE_CONTENT_APPROVAL=False`
- [x] Add instructions for this parameter to the wiki

**Comment by chouseknecht** [comment]
See https://github.com/ansible/galaxy_ng/wiki/Enabling-auto-certification

**Comment by newswangerd** [comment]
Moved to issues.redhat.com/
