### ISSUE TITLE
Upgrade pulpcore dependency to 3.4.0

### ISSUE THREAD

**Issue by cutwater** [ansible/galaxy_ng#209]
Currently `galaxy_ng` requires `pulpcore>=3.0,<3.4`, while `pulp_container` requires `pulpcore>=3.4`. In order to use `galaxy_ng` with `pulp_container`, pulpcore version must be upgraded.

**Comment by Spredzy** [comment]
Note: requires update on the README.md and https://github.com/ansible/galaxy_ng/wiki/End-User-Installation to replace `git+https://github.com/pulp/pulpcore.git@3.3.0#egg=pulpcore` by `git+https://github.com/pulp/pulpcore.git@3.4.0#egg=pulpcore`
