### ISSUE TITLE
Import Task "2857" failed: 'str' object is not a mapping 

### ISSUE THREAD

**Issue by pabelanger** [ansible/galaxy_ng#213]
## Bug Report
We are still having an issue importing some collections into galaxy,  this is even after passing ansible-galaxy importer.

Starting import: task_id=2857, artifact_id=2857 
Getting doc strings via ansible-doc 
Import Task "2857" failed: 'str' object is not a mapping 

##### STEPS TO REPRODUCE

you can see log of job located at:
https://dashboard.zuul.ansible.com/t/ansible/build/2d2c159832ba4ed8913ce94fce38ad72 

##### ACTUAL RESULTS

```

```

**Comment by chouseknecht** [comment]
Is this a community galaxy issue or Automation Hub issue?

**Comment by pabelanger** [comment]
galaxy.a.c, haven't tested on AH yet.

**Comment by awcrosby** [comment]
This was a known issue for older version of `galaxy-importer` package, and popped up again since we temporarily reverted `galaxy-importer` version on galaxy.ansible.com. We have just deployed latest `galaxy-importer` so this can be closed.

**Comment by pabelanger** [comment]
@awcrosby when would you say it was deployed? I'd like to confirm the last failure, was before the upgrade.

**Comment by awcrosby** [comment]
@pabelanger 2020-06-01 9:58am ET
