### ISSUE TITLE
Story: Configure and manage content sync

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy_ng#22]
As an admin of a private AH, I want to:

- Configure the remote source of content, including: URL, API token
- Initiate the content sync task
- Know the status of the sync task and view any logs
- ~~Set the provenance for the remote (e.g., local, Red Hat, Community)~~

**Comment by chouseknecht** [comment]
Related to #17

**Comment by chouseknecht** [comment]
We need to decide in which repository sync'd content will land. Our original assumption is that it would land in the 'golden' or default repository, and that's probably not what we want. Ideally we want the user to provide a repository name, and as part of the sync that repository gets created if it does not already exist.

**Comment by chouseknecht** [comment]
Based on the discussion this morning (7 July) with John:

- [ ] only allow the sync'ing of content from community and c.rh.c. (Guessing we'll expand this in the future, but for now we agreed to limit it.)
- [ ] during installation, the installer will create the following default repositories:

    | Repository | Description |
    | ----------- | ----------- |
    | staging       | staging for private collection versions |
    | rejected      | rejected private collection versions |
    | published.  | certified or accepted private collection versions |
    | community | collections sync'd from galaxy.ansible.com
    | rh-certified | collections sync'd from c.rh.c |

- [ ] The UI will enable an admin user to configure the remote for the *community* repository and the remote for the *rh-certified* repository.
- [ ] For the *community* remote, the user will be required to provide a URL, token, and a string representing a requirements.yml file. 
- [ ] For the *rh-certified* remote, the user will be require to provide a URL and token. (Question: is an `auth_url` required? Believe the CLI requires this when authentication with c.rh.c)

**Comment by alikins** [comment]
For the rh-certified remote, it may make sense to provide a cloud.redhat.com galaxy_ng api for the remote config info in one place. (for ex, possibly as part of the synclists api. Or on a my-repositories endpoint if we add that). 

Goal being only thing needed to setup sync of rh-certified from cloud.redhat.com would be login info, and c.r.c galaxy_ng could provide a list of the possible remotes for that user/org/account/

**Comment by chouseknecht** [comment]
@rochacbruno @ZitaNemeckova 

Notes from the PM Sync meeting on 3 August:

- For the community remote, the `requirements.yml` should be an upload, not a copy-paste field
- In our documentation we can tell users how to syntax check their YAML before uploading it
- The backend is not expected to provide YAML syntax checking
