### ISSUE TITLE
Not Found: /api/galaxy/v3/artifacts/collections/ when uploading a collection

### ISSUE THREAD

**Issue by Spredzy** [ansible/galaxy_ng#226]
##### SUMMARY

User presented with a Not found message when trying to upload a collection. This was working a few days ago (~2/3 days).

##### STEPS TO REPRODUCE

  * Install as per the instruction in the `README.md`
  * Create a collection in `My Namespace` (ie. `awx`)
  * Upload an `awx.awx` collection

##### EXPECTED RESULTS

  * Collection to be uploaded

##### ACTUAL RESULTS

  * `pulp: django.request:WARNING: Not Found: /api/galaxy/v3/artifacts/collections/`

![Screenshot_2020-06-09 Ansible Automation Hub](https://user-images.githubusercontent.com/1191411/84117501-e88e9800-aa31-11ea-80cb-70545fcdfdcf.png)

```
"versions": [
        {
            "component": "pulpcore",
            "version": "3.4.1"
        },
        {
            "component": "pulp_container",
            "version": "1.4.1"
        },
        {
            "component": "pulp_ansible",
            "version": "0.2.0b13"
        },
        {
            "component": "galaxy_ng",
            "version": "4.2.0a8"
        }
    ],
```

**Comment by Spredzy** [comment]
`E_CANT_REPRODUCE`

**Comment by Spredzy** [comment]
Re-opening as it is still reproducing.

Guts feeling: There is a race condition happening somewhere

```
roles:
    - pulp_database
    - pulp_workers
    - pulp_resource_manager
    - pulp_webserver
    - pulp_content
    - chouseknecht.ansible_galaxy_config
```

Role `chouseknecht.ansible_galaxy_config` is somewhat runs too fast/early, pulp hasn't fully finished to initialize or something. Sometimes role runs when initialization has finished and things work, sometimes it does it too early and things end up broken.

if I do the following, it constantly works:

```---
- hosts: localhost
  roles:
    - pulp_database
    - pulp_workers
    - pulp_resource_manager
    - pulp_webserver
    - pulp_content

- hosts: localhost
  tasks:
    - pause:
         minute: 1

    - include_role:
        name: chouseknecht.ansible_galaxy_config```

**Comment by chrismeyersfsu** [comment]
`curl -X POST -H "Authorization: Token 5ca2da0ef759e4be93e686fe023ffb42ed8aa5eb" http://ec2-54-211-208-93.compute-1.amazonaws.com/api/galaxy/v3/artifacts/collections/ -F file=@foo-bar-1.0.0.tar.gz`

This started with a 404 from `ansible-galaxy collection publish foo-bar-1.0.0.tar.gz`
I recreated what publish does as a curl command. Also got a 404. But when I visit the url in question in the browser, it exists. The 404 seems to be based on the content I submit.
Tracing the code leads me here https://github.com/ansible/galaxy_ng/blob/stable/galaxy_ng/app/api/v3/viewsets/collection.py#L117 but the 404 is coming from Pulp https://github.com/pulp/pulp_ansible/blob/8e2d15e5d987df2a4ae70807783afabdefb8dc61/pulp_ansible/app/galaxy/v3/views.py#L133
Some prints tell me that base_path='automation_hub'. 

```
export LD_LIBRARY_PATH=/opt/rh/rh-postgresql10/root/usr/lib64
export PULP_SETTINGS=/etc/pulp/settings.py
export DJANGO_SETTINGS_MODULE="pulpcore.app.settings"
source /usr/local/lib/pulp/bin/activate
```

```
django-admin dbshell
automationhub=> select * from ansible_ansibledistribution;
       basedistribution_ptr_id        |            repository_id             | repository_version_id
--------------------------------------+--------------------------------------+-----------------------
(0 rows)
```

Tower inits galaxy + pulp in the install via https://github.com/ansible/tower-packaging/blob/devel/setup/roles/automationhub/templates/install.yml.j2#L58
This calls the below role.
https://github.com/chouseknecht/ansible_galaxy_config/blob/master/tasks/create_repositories.yml#L30

I manually re-ran the create distribution step of the above playbook and get a task back.

`99fcefc4-4427-49c4-93b9-600fe849710a` <-- my task id for the distribution

```
automationhub=> select * from core_worker;
               pulp_id                |         pulp_created          |       pulp_last_updated       |               name               |        last_heartbeat         | gracefully_stopped | cleaned_up
--------------------------------------+-------------------------------+-------------------------------+----------------------------------+-------------------------------+--------------------+------------
 52a2235f-efa9-40d9-84d3-2ecace507533 | 2020-06-27 01:25:22.639341+00 | 2020-06-27 01:25:57.348169+00 | 16586@ip-10-0-3-155.ec2.internal | 2020-06-27 01:25:57.348185+00 | f                  | t
 91a56e82-d9e3-4eee-a467-3e3d1f71ea36 | 2020-06-27 01:25:21.599156+00 | 2020-06-27 01:26:15.166724+00 | 16520@ip-10-0-3-155.ec2.internal | 2020-06-27 01:26:15.166735+00 | f                  | t
 9de3388a-b967-4a54-8374-4ec745410884 | 2020-06-27 01:25:58.439862+00 | 2020-06-27 01:25:58.439894+00 | 17567@ip-10-0-3-155.ec2.internal | 2020-06-27 03:05:41.478428+00 | f                  | f
 abf1b66f-f254-4f1a-80a8-a08b0d2fbeb3 | 2020-06-27 01:25:24.632948+00 | 2020-06-27 01:25:57.383218+00 | resource-manager                 | 2020-06-27 03:05:44.884024+00 | f                  | t
 10b1f2c9-1c37-403e-9d72-b4da0955f438 | 2020-06-27 01:25:57.286576+00 | 2020-06-27 01:25:57.286613+00 | 17523@ip-10-0-3-155.ec2.internal | 2020-06-27 03:05:44.884023+00 | f                  | f
```

```
automationhub=> select * from core_task where id='99fcefc4-4427-49c4-93b9-600fe849710a';
               pulp_id                |         pulp_created          |       pulp_last_updated       |  state   |                  name                  | started_at | finished_at | error |              worker_id               | parent_task_id | task_group_id
--------------------------------------+-------------------------------+-------------------------------+----------+----------------------------------------+------------+-------------+-------+--------------------------------------+----------------+---------------
 99fcefc4-4427-49c4-93b9-600fe849710a | 2020-06-27 01:26:02.512917+00 | 2020-06-27 01:26:15.161133+00 | canceled | pulpcore.app.tasks.base.general_create |            |             |       | 91a56e82-d9e3-4eee-a467-3e3d1f71ea36 |                |
(1 row)
```

Now, looking at the Tower installer, I see that some pulp installation happens shortly before the galaxy init data script runs. My theory is that all of the services aren't up and running so the task is dropped on the floor.

My manually resubmitted distribution creation succeeds.


### Recommendation 
* Ask pulp if this is common/plausible.
* Before submitting API requests to pulp (in @chouseknecht role) check that pulp is up and "healthy"
* Again, in @chouseknecht role, poll on the resulting job until a timeout

Note: Another view of "things didn't go right" is if a distribution never appears at: http://ec2-54-211-208-93.compute-1.amazonaws.com/pulp/api/v3/distributions/ansible/ansible/
