### ISSUE TITLE
Story: Capture and surface dependency metadata

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy_ng#23]
As part of defining and creating an execution environment, collection authors will be able to include system level dependencies in a new metadata file. AH will need to check if the file is present.

When present, the importer should lint the file and capture any errors and warnings. It should also ingest the file and store the contents in the database. The API should return the contents of the file in the collection details, and the UI should surface it as well.

See https://docs.google.com/document/d/1Mi04XC1AsWIVkYt-kWCNUWcK3cWnQhHZFijZlaOLLn8/edit?ts=5e1c45dc for the dependency metadata details.

**Comment by AlanCoding** [comment]
Google doc linked there is

> Automation Platform Execution Environment PRD

Another doc https://docs.google.com/document/d/1aqE5g5VxrV17syFzqSTVDa5Vg1rqQJlUml0dDve9MCs/edit

> Automation Platform Execution Environments

The most recently active doc https://docs.google.com/document/d/1Lc8xMUrTlDVAxO0MFfHRCVORKlAXNGoBcj_r4UII8Qk/edit#

> ansible-builder

**Comment by newswangerd** [comment]
Moved to issues.redhat.com/
