### ISSUE TITLE
AH import error: No such container

### ISSUE THREAD

**Issue by anshulbehl** [ansible/galaxy_ng#230]
##### SUMMARY

Collection import is showing an error in AH

##### STEPS TO REPRODUCE

Issue happened with collection version below:
https://galaxy.ansible.com/f5networks/f5_modules
version: 1.4.0
Present here: https://cloud.redhat.com/ansible/automation-hub/my-imports?namespace=f5networks&name=f5_modules&version=1.4.0

##### EXPECTED RESULTS

No error

##### ACTUAL RESULTS

```
Running sanity test 'compile' with Python 3.6 
Running sanity test 'compile' with Python 3.7 
Running sanity test 'compile' with Python 3.8 
Running sanity test 'empty-init' with Python 3.6 
Running sanity test 'future-import-boilerplate' with Python 3.6 
Running sanity test 'ignores' 
Running sanity test 'line-endings' with Python 3.6 
Running sanity test 'metaclass-boilerplate' with Python 3.6 
Running sanity test 'no-assert' with Python 3.6 
Running sanity test 'no-basestring' with Python 3.6 
Running sanity test 'no-dict-iteritems' with Python 3.6 
Running sanity test 'no-dict-iterkeys' with Python 3.6 
Running sanity test 'no-dict-itervalues' with Python 3.6 
Running sanity test 'no-get-exception' with Python 3.6 
Running sanity test 'no-illegal-filenames' with Python 3.6 
Running sanity test 'no-main-display' with Python 3.6 
Running sanity test 'no-smart-quotes' with Python 3.6 
Running sanity test 'no-unicode-literals' with Python 3.6 
Running sanity test 'pep8' with Python 3.6 
Running sanity test 'pylint' with Python 3.6 
rpc error: code = Unknown desc = Error: No such container: 4972187f94ce0138714b608a8c92af1a107e5668799fce461c753e6ac49b7916 
Done
```

```

```

**Comment by anshulbehl** [comment]
@awcrosby

**Comment by awcrosby** [comment]
Looking at logs, this collection hit the galaxy-importer ansible-test job timeout during pylint, we need to increase the timeout, and should make it configurable in openshift.

**Comment by awcrosby** [comment]
Timeout parameter was added. However increasing memory size of container was able to resolve this in test environments, bumping `IMPORTER_MEMORY_LIMIT` to `2Gi`

**Comment by chouseknecht** [comment]
Will deploy this next week when @cutwater returns

**Comment by awcrosby** [comment]
This change has been made in AH Prod.
