### ISSUE TITLE
Fix developer wiki init data

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/galaxy_ng#233]
Simple 1-line fix.

The wiki development environment setup worked for me a few weeks ago. I wasn't able to find the change that caused it to start failing but the below fixes it. Feels like it has something to do with packaging, rightfully so, not including the dev init data. https://github.com/ansible/galaxy_ng/wiki/Development-Setup

```
diff --git a/Development-Setup.rest b/Development-Setup.rest
index 33ea46e..b741983 100644
--- a/Development-Setup.rest
+++ b/Development-Setup.rest
@@ -75,7 +75,7 @@ Next, run the following steps to build your local development environment:
    .. code-block:: console
-       $ ./compose run --rm -e PULP_FIXTURE_DIRS='["/app/dev/automation-hub"]' \
+       $ ./compose run --rm -e PULP_FIXTURE_DIRS='["/src/galaxy_ng/dev/automation-hub/"]' \
         api manage loaddata initial_data.json
    Alternative way (manually):
```

**Comment by chouseknecht** [comment]
Was able to reproduce. Thanks @chrismeyersfsu for reporting this.

**Comment by chouseknecht** [comment]
Fixed the wiki. While testing the above, found the following bugs:

- The compose file expects `dev/standalone/docker-compose-ui.yml`, but the actual file name is `docker-compose.ui.yml`. Fixed the file name in both the standalone and insights folders.
- Fixture data does not associate the `admin` user with the `system:partner-engineers` group
