### ISSUE TITLE
Fix example collection upload playbook

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/galaxy_ng#238]
https://github.com/ansible/galaxy_ng/wiki/Automating-Collection-Uploads

Replace the example playbook with the two lines below.

```
git clone git@gist.github.com:9780204a121aa2e72fd61469d1b8020d.git example_playbook
cd example_playbook && ansible-playbook upload_collection.yml
```

* Create gist so multiple files can easily be consumed by the reader
* Align default playbook galaxy api with developer port and endpoints
* Add working, valid collection.
* Easily generate arbitrary namespace + collection names for testing

**Comment by chouseknecht** [comment]
- Modified the example playbook with the Dev environment URL
- Created a gist, as suggested
- Added gist copy instructions
- Added link to the referenced collection artifact

Let me know if the updated Wiki page addresses your suggestions adequately. 

Thanks!

**Comment by chouseknecht** [comment]
Think this has been addressed. Closing.
