### ISSUE TITLE
Surface MANIFEST.json and DIGEST.json in CollectionVersion serializer

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy_ng#24]
Required by the `verify` command planned for Ansible 2.10. This work is being done on the Pulp side here: https://pulp.plan.io/issues/7572. Once that's ready we'll need to surface in the AH v3 API.

**Comment by alikins** [comment]
Looks like https://pulp.plan.io/issues/7572  is the updated bug.

**Comment by newswangerd** [comment]
Moved to issues.redhat.com/
