### ISSUE TITLE
Collection detail response contains invalid href

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy_ng#247]
In our CI environment this endpoint https://ci.cloud.redhat.com/api/automation-hub/v3/collections/autohubtest2/collection_dep_a_hlrknkqw/ returns the following response object: 

```
{
    "href": "/pulp_ansible/galaxy/automation-hub/api/v3/collections/autohubtest2/collection_dep_a_hlrknkqw/",
    "created_at": "2020-02-21T23:01:52.727205Z",
    "updated_at": "2020-02-21T23:01:52.727232Z",
    "namespace": "autohubtest2",
    "name": "collection_dep_a_hlrknkqw",
    "deprecated": false,
    "versions_url": "/pulp_ansible/galaxy/automation-hub/api/v3/collections/autohubtest2/collection_dep_a_hlrknkqw/versions/",
    "highest_version": {
        "href": "/pulp_ansible/galaxy/automation-hub/api/v3/collections/autohubtest2/collection_dep_a_hlrknkqw/versions/1.0.0/",
        "version": "1.0.0"
    }
}
```

Notice the invalid `href` value in the above response. It should not contain `/pulp_ansible/galaxy`.

This issue is blocking work related to adding token support to content sync in the [pulp_installer](https://github.com/pulp/pulp_ansible) project. For details see: https://github.com/pulp/pulp_ansible/pull/326#issuecomment-644313611

**Comment by alikins** [comment]
The serializers used by the pulp collection viewsets (and therefore galaxy_ng collection viewsets) base the values for 'href' on url reverse() lookups, and end up with the pulp paths.

May mean galaxy_ng viewsets need to provide their own serializer. 

But may be able to parameterize the reverse()'s to handle both cases. Possibly via providing a ViewSet.get_serializer_context()

**Comment by chouseknecht** [comment]
@alikins IIRC, we decided on option 1 during standup on Tuesday (16 June).

**Comment by alikins** [comment]
https://github.com/ansible/galaxy_ng/pull/254/ has a proposed fix that doesn't rely on any pulp_ansible changes.

It seems to work, but might be a bit weird. Could probably de-weirdify it a bit with some changes in pulp_ansible. The pulp_ansible changes would likely be similar (taking the url namespace into account, etc).
