### ISSUE TITLE
Galaxy becomes non functional once admin user password is updated

### ISSUE THREAD

**Issue by Spredzy** [ansible/galaxy_ng#251]
##### SUMMARY

After install everything works fine. One can create namespaces and upload collections just fine.
If one goes to user > admin > edit and update names + email + password then the interface starts mal functioning and throwing `403 Forbidden` for every API call. One can see `Invalid username/password.` as part of the API call response.

While one can succesfully log back out and in again with those credentials, every API call will fail.

##### STEPS TO REPRODUCE

  1. Install Galaxy (and upload content - optional)
  2. Update admin name  + email + passwords
  3. Try to navigate galaxy

##### EXPECTED RESULTS

Things to work smoothly

##### ACTUAL RESULTS

403 Forbidden for each API call with `Invalid username/password.` in the response

**Comment by chouseknecht** [comment]
This has to do with the galaxy_ng API making calls to the Pulp API. We're working on replacing API calls with direct database access via viewset subclassing. For now, if you update the admin password, you have to update `x_pulp_api_password` in `settings.py`.

**Comment by Spredzy** [comment]
Thanks for info and workaround :+1:

**Comment by chouseknecht** [comment]
The end-user install playbook has been updated to address this. Over time API calls to Pulp will be replace with direct database access. Closing.
