### ISSUE TITLE
Story: Surface playbooks

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy_ng#252]
It appears the collection spec is being expanded to include playbooks. See https://github.com/ansible/ansible/pull/67435

There's also a PRD spec in process: 
https://docs.google.com/document/d/1hwIA1QrqedVNH-h1OUpXUfXxR5lq4Xr90e_kAyllcIA/edit?usp=sharing

We need to decide if/how to surface playbooks in Galaxy.

**Comment by bcoca** [comment]
fyi, there has also been talk about 'template/files/vars' shared at collection level.
