### ISSUE TITLE
Importer: Require a collection tag that matches tag list

### ISSUE THREAD

**Issue by awcrosby** [ansible/galaxy_ng#255]
When importing in Automation Hub and Community Galaxy, `galaxy-importer` will require the collection metadata include at least one tag that matches the following tag list:

cloud
linux
networking
storage
security
windows
infrastructure
monitoring
tools
database
application

**Comment by awcrosby** [comment]
@thedoubl3j @anshulbehl please confirm I captured this feature request correctly

**Comment by anshulbehl** [comment]
@awcrosby  network tag is now changed to networking
https://github.com/ansible/galaxy_ng/issues/232

**Comment by thedoubl3j** [comment]
lgtm aside from @anshulbehl find
