### ISSUE TITLE
 django.db.utils.IntegrityError: duplicate key value violates unique constraint "ansible_collectionimport_task_id_9d08fd06_pk"

### ISSUE THREAD

**Issue by prakash-marina** [ansible/galaxy_ng#257]
Steps to reproduce:

Version : v4.2.0a8

Just configure DB, Redis and Storage(S3).

Update the env configs.

Create Namespace and try uploading.

First time it works fine, next time it fails for any uploads. while downloads are working fine.

 django.db.utils.IntegrityError: duplicate key value violates unique constraint "ansible_collectionimport_task_id_9d08fd06_pk"

api_1               | /venv/lib64/python3.6/site-packages/storages/backends/s3boto3.py:341: UserWarning: The default behavior of S3Boto3Storage is insecure and will change in django-storages 1.10. By default files and new buckets are saved with an ACL of 'public-read' (globally publicly readable). Version 1.10 will default to using the bucket's ACL. To opt into the new behavior set AWS_DEFAULT_ACL = None, otherwise to silence this warning explicitly set AWS_DEFAULT_ACL.
api_1               |   "The default behavior of S3Boto3Storage is insecure and will change "
api_1               | Internal Server Error: /api/automation-hub/v3/artifacts/collections/
api_1               | Traceback (most recent call last):
api_1               |   File "/venv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
api_1               |     return self.cursor.execute(sql, params)
api_1               | psycopg2.errors.UniqueViolation: duplicate key value 
violates unique constraint "ansible_collectionimport_task_id_9d08fd06_pk"  
api_1               | DETAIL:  Key (task_id)=(985264c3-2993-4c7d-8c86-1ab1aeb78408) already exists.
api_1               |
api_1               | 
api_1               | The above exception was the direct cause of the following exception:
api_1               |
api_1               | Traceback (most recent call last):
api_1               |   File "/venv/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
api_1               |     response = get_response(request)
api_1               |   File "/venv/lib64/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
api_1               |     response = self.process_exception_by_middleware(e, request)
api_1               |   File "/venv/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response

**Comment by chouseknecht** [comment]
What does `Just configure DB, Redis and Storage(S3)` mean? There's no documentation yet on how to do these things, so wondering what you changed.

**Comment by prakash-marina** [comment]
changed the following configs.

PULP_DB_HOST to the database that was created using RDS (Followed the DB migration steps as well)
PULP_REDIS_HOST (Configured my custom cache cluster)

Followed Pulp documentation to setup S3 Django storage.

https://docs.pulpproject.org/installation/storage.html

Everything is working fine, except the upload part failing with duplicate key value. 

It was working fine on previous version. 

Thanks,
Prakash

**Comment by chouseknecht** [comment]
I think this has been fixed. If not, please re-open at [issues.redhat.com](https://issues.redhat.com/projects/AAH/)
