### ISSUE TITLE
Content Sync: Create default synclist and associated repository/distribution on login

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy_ng#264]
Subtask of #17 

- This is for c.rh.c only. It does not apply when running a local Galaxy.
- Whenever a subscriber logs in, check if the default synclist for their organiztion exists, and if not, create it.
- Default the synclist name, repository name, and distribution name to the group number + '-synclist'.

**Comment by alikins** [comment]
@chouseknecht

>  Default the synclist name, repository name, and distribution name to the group number + '-synclist'.

If I understand correctly, for a custom in account "6297347"  that is in the group "rh-identity-account:6297347", the default synlists names would be something roughly like:

- 6297347-synclist

One small issue is that don't store the plain account number "6297347" on it's own anywhere in the data. It only exists as a substring in the group name "rh-identity-account:6297347".

Very easy to parse out the account number in that case of course, but it feels like something that would very likely break in the future.  if for ex:

- we stop using the rh-identity-account prefix for group name
- we allow standalone systems to use arbitrary group names  (not likely an issue for synclists, but if there are other features that rely on account number in the future)

Nothing that blocks anything now, I'll add a 'record account number in the db' issue to keep track of it.

**Comment by chouseknecht** [comment]
> @chouseknecht
> 
> > Default the synclist name, repository name, and distribution name to the group number + '-synclist'.
> 
> If I understand correctly, for a custom in account "6297347" that is in the group "rh-identity-account:6297347", the default synlists names would be something roughly like:
> 
> * 6297347-synclist
> 

Yes. That seems right.

> One small issue is that don't store the plain account number "6297347" on it's own anywhere in the data. It only exists as a substring in the group name "rh-identity-account:6297347".
> 
> Very easy to parse out the account number in that case of course, but it feels like something that would very likely break in the future. if for ex:
> 
> * we stop using the rh-identity-account prefix for group name
> * we allow standalone systems to use arbitrary group names  (not likely an issue for synclists, but if there are other features that rely on account number in the future)
> 
> Nothing that blocks anything now, I'll add a 'record account number in the db' issue to keep track of it.

That seems look idea. +1

**Comment by chouseknecht** [comment]
We decide in the Pulp/Galaxy Check-in meeting on 7 July:

- on login create a unique distribution for the org, if it does not exist, and associate it with the *published* repo
- the first time a user adds a collection to the org's denylist, create a repo and associate it with the distribution, and then start a task that copies collection version from the *published* repo into the new repo

**Comment by alikins** [comment]
This is all concentrated in the pr https://github.com/ansible/galaxy_ng/pull/315 now. Most of the work specified in this issue is done. Possibly a few hours for docs/tests/etc, but functionality wise it works in #314

**Comment by alikins** [comment]
https://github.com/ansible/galaxy_ng/pull/315

**Comment by alikins** [comment]
implemented in #315
