### ISSUE TITLE
API: Curate content in org sycnlist repositories

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy_ng#265]
Subtask of #17

When subscribers modify their synclist or the golden repository versions changes, AH needs to add/remove content from the associated repositories.

- [ ] Understand the 'Pulp way' of curating the content in a given org repository 
- [ ] Understand and mitigate any potential performance challenges.

**Comment by chouseknecht** [comment]
Notes from Pulp/Galaxy check-in meeting:

* Curate content via task code that produces an org repository version
    * Inside task code run db queries that include all content from golden repo, subtracting denylist items. This can be done via Django ORM querysets.
* Performance suggestions:
    * For synclist changes:
        * Could we use a periodic task as a way to batch the changes?
        * We could also possibly rev org repos when a local sync is initiated?
    * For content change in the golden repo:
       * kick-off n number of tasks where n is the number of org repos.

**Comment by alikins** [comment]
This tasks probably needs about 8-10 hours of work on it.

**Comment by alikins** [comment]
https://github.com/ansible/galaxy_ng/pull/315

**Comment by alikins** [comment]
Implemented in #315
