### ISSUE TITLE
Content Sync: On synclist creation, create the repository

### ISSUE THREAD

**Issue by alikins** [ansible/galaxy_ng#267]
When creating a synclist, ensure that the curated repo and distribution exists, and create them if needed.

This is related to https://github.com/ansible/galaxy_ng/issues/264 and https://github.com/ansible/galaxy_ng/issues/265

Current synclist API doesn't do this, so this is an add on for synclist API.

The repository name, and Distribution name and base_path should be unique and likely need to be based on account_number (as mentioned in  https://github.com/ansible/galaxy_ng/issues/264).

(There is WIP code for this, so adding issue for the pr)

**Comment by chouseknecht** [comment]
We decide in the Pulp/Galaxy Check-in meeting on 7 July:

- on login create a unique distribution for the org, if it does not exist, and associate it with the published repo
- the first time a user adds a collection to the org's denylist, create a repo and associate it with the distribution, and then start a task that copies collection version from the published repo into the new repo.

**Comment by alikins** [comment]
https://github.com/ansible/galaxy_ng/pull/315 is the WIP for this.

**Comment by alikins** [comment]
Some work needed here, mostly tweaks related to pr review. Probably ~6 hours of work.

**Comment by alikins** [comment]
https://github.com/ansible/galaxy_ng/pull/315
