### ISSUE TITLE
Partner Page sorting default is broken and icon shows reverse of state

### ISSUE THREAD

**Issue by ironfroggy** [ansible/galaxy_ng#27]
##### SUMMARY
On the Partner and Namespace listing pages, by default neither available sort option (Ascending Name or Descending Name) is set. This makes the initial lists of namespaces scrambled, but it also means when the user tries to change the sort, which initially reflects the Descending Name sort, gets flipped in reverse and doesn't match the actual sort being used.

##### STEPS TO REPRODUCE
Load the partner page: https://cloud.redhat.com/ansible/automation-hub/partners

##### EXPECTED RESULTS
A navigable list of namespaces with search and sort options

##### ACTUAL RESULTS
A confusing list of namespaces and a sort option that reflects the incorrect state.

**Comment by newswangerd** [comment]
@ironfroggy I think these changes just need to be deployed to stable. It looks like its working in CI
