### ISSUE TITLE
RBAC: draft use cases

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy_ng#273]
Subtask of #21

Write out the clear set of use cases for RBAC for review with @jonnyfiveiq  and @cutwater.

**Comment by alikins** [comment]
Some notes on this at: https://hackmd.io/kZ1oYp8TTkeuC5KL_ffjGQ

**Comment by chouseknecht** [comment]
galaxy_ng specific use cases: https://hackmd.io/JisLkfyeT2myAD2khEwU0A
