### ISSUE TITLE
API: Cant add new links to namespaces

### ISSUE THREAD

**Issue by newswangerd** [ansible/galaxy_ng#277]
Adding new links on the namespace form is broken.

**Comment by ironfroggy** [comment]
Observations:
- Filling out a new link and clicking "Save" does not add a new link
- A link is only added by clicking the "+" and creating another, unfilled pair of link fields
- Users are going to be confused by this behavior and expect "Save" to include the last link fields
- Error messages for the link fields are not associated with a specific link, hard to find the problem
- Links without http:// _are_ valid and users will enter them. "Enter a valid URL" does not make it clear what is missing, either. Schema can be added if missing.
- Every time the namespace is saved, the order of the links is reversed.

**Comment by newswangerd** [comment]
Moved to issues.redhat.com/
