### ISSUE TITLE
UI: Configure and manage content sync

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy_ng#281]
Subtask of #22

The UI will enable an admin user to configure the remote for the *community* repository and the remote for the *rh-certified* repository.

- For the *community* remote, the user will be required to provide a URL, token, and a string representing a `requirements.yml` file. 
- For the *rh-certified* remote, the user will be require to provide a URL and token. There will be no option for a `requirements.yml` file, as it conflicts with the denylist being created on c.rh.c. (Question: is an `auth_url` required? Believe the CLI requires this when authentication with c.rh.c).
- For each remote, the admin user can set the `policy` value. The default policy will be `on-demand`. Valid options are here: https://docs.pulpproject.org/workflows/on-demand-downloading.html.
- For each remote, the UI will also provide a `Sync Now` button to initiate the sync process.

**Comment by newswangerd** [comment]
As far as I can tell, this is the data we need to make the current design work:

General repo fields:
- Local repo URL
- Remote repo URL (for configuring remotes)
- Remote repo API token
- Remote repo SSO server (to support red hat sso)
- Name
- Last updated
- Sync status (whether or not a sync is in progress)
- Last sync date
- Owner (group that owns the repo)
- Is the repo remote or local
- is the repo searchable
- Is the repo the default repo

@bmbouter was talking about making pulp objects taggable. Tags might work for the last three.

To support Galaxy sync with requirements.yml:
- Requirements.yml blob

**Comment by ZitaNemeckova** [comment]
Needs about a week after API is ready.

**Comment by ZitaNemeckova** [comment]
https://github.com/ansible/ansible-hub-ui/pull/186
