### ISSUE TITLE
API: Update org repositories when new collection version published

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy_ng#285]
Subtask of #20 

For c.rh.c, when a collection version is promoted from the *staging* repository to the *published* repository, the subscriber org repositories must be updated with the new artifact. 

The promotion event has to:
 - Kick-off n number of tasks, where n is the number of org repos
 - Each task will:
     - run a db query that includes all collection versions from the *certified* repo, subtracting any denylist colletions for the org
     - produce an org repository version containing the result of the query

**Comment by chouseknecht** [comment]
Notes from Galaxy/Pulp check-in meeting regarding task development: 
-  https://docs.pulpproject.org/plugins/plugin-writer/concepts/index.html#tasks
    - Group task report - reports progress on a group of tasks
    - Could be used to surface promotion status in UI

**Comment by alikins** [comment]
https://github.com/ansible/galaxy_ng/pull/315 is the WIP for this.

**Comment by alikins** [comment]
This will be in https://github.com/ansible/galaxy_ng/pull/315/. 

This subtask is where most of the ~8-10 hours of work needed for https://github.com/ansible/galaxy_ng/issues/265#issuecomment-671365304 comes from.

**Comment by alikins** [comment]
https://github.com/ansible/galaxy_ng/pull/427  adds an api endpoint for triggering a curate on all synclist repos associated with golden repo at  /api/automation-hub/_ui/v1/repo/str:repo_name/curate/

https://github.com/ansible/galaxy_ng/pull/432  also provides a mechanism for also triggering the golden repo -> synclist-repos curration when content is 'moved' in or out of the golden repo

**Comment by alikins** [comment]
See also https://github.com/ansible/galaxy_ng/issues/428

**Comment by alikins** [comment]
One implementation is in #432
