### ISSUE TITLE
API: API versioning

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy_ng#29]
Develop and document a formal process for introducing breaking API changes. For example, with the introduction of content sync we're going planning to remove publish support to `/artifacts/collections`. A good process would allow us to gracefully communicate changes to users and the Ansible platform teams, and deprecated older versions over time.

**Comment by chouseknecht** [comment]
We also need to decide if we're going to extend v3 or start a v4.

**Comment by newswangerd** [comment]
Moved to issues.redhat.com/
