### ISSUE TITLE
Add Documentation Links for Galaxy

### ISSUE THREAD

**Issue by jamesmarshall24** [ansible/galaxy_ng#291]
### Use Case

A customer is redirected to use a galaxy, but may not be familiar with the feature in Ansible. A link in the UI to the Galaxy user guide/documentation may be helpful.

### Proposed Solution

Add a link to: [https://docs.ansible.com/ansible/latest/galaxy/user_guide.html](https://docs.ansible.com/ansible/latest/galaxy/user_guide.html) somewhere in the web UI that can be seen while looking over roles/collection results.

Something like:

"Ansible Galaxy User Guide"

or

"Read more about Ansible Galaxy in our documentation"

### Implementation

Documentation and usability change

**Comment by chouseknecht** [comment]
This is an issue for [Community Galaxy](https://github.com/ansible/galaxy), and should be filed there.
