### ISSUE TITLE
Importer: Build and run ansible-test via Podman

### ISSUE THREAD

**Issue by bmclaughlin** [ansible/galaxy_ng#294]
We're currently able to build and run images via Docker in stand-alone mode (https://github.com/ansible/galaxy-importer/pull/74), this issue is for tracking the code changes and effort to document the configuration needed to do the same via Podman.

**Comment by chouseknecht** [comment]
Subtask of #6

**Comment by newswangerd** [comment]
Moved to issues.redhat.com/
