### ISSUE TITLE
UI: Provide indication of collection version state

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy_ng#309]
Feedback from RH Partner Engineer team that partners would like an indicator for the state of a collection version. Would be one of: waiting for review, rejected, certified

- Applies to c.rh.c, or in standalone mode when auto certification is not enabled.
- Suggestion during discussion with RH Partner Engineers is to put this on My Imports. The UI will need to evaluate the repository in which the collection version exists in order to determine its state.

**Comment by chouseknecht** [comment]
Subtask of #20

**Comment by ZitaNemeckova** [comment]
https://github.com/ansible/ansible-hub-ui/pull/190
