### ISSUE TITLE
Artifact Upload: Invalid filename errors do not include an error code

### ISSUE THREAD

**Issue by ironfroggy** [ansible/galaxy_ng#31]
```json
{
  "status": "400",
  "code": null,
  "title": "Invalid input.",
  "detail": "Invalid version string name from filename a-wrong-name.tar.gz. Expected semantic version format.",
  "source": {"parameter": "filename"}
}
```

When given an invalid filename, the error response body does not include a `code` as dictated by the standard error format. The same error on Galaxy gives the error code `invalid` so it probably makes sense to be consistent here.

**Comment by alikins** [comment]
@ironfroggy 

> When given an invalid filename, the error response body does not include a code as dictated by the standard error format. The same error on Galaxy gives the error code invalid so it probably makes sense to be consistent here.

Yeah, I would agree with that as expected behavior. 

Looking at the code, I don't think it's fixed yet, but see how. Should be easy fix.

**Comment by hendersonreed** [comment]
Tests have been added to our iqe-automation-hub repo and verify this fix, so we should be good to go.
