### ISSUE TITLE
Partner Page search functionality issues

### ISSUE THREAD

**Issue by ironfroggy** [ansible/galaxy_ng#32]
The search on the partner page exhibits a number of issues, enumerated here for discussion and correction:

- Is case-sensitive, but users may type names like "IBM" when they want the namespace "ibm"
- Is exact-only, so only useful for entering the exact single namespace you want, not actually a search
- Matches against namespace, but not the visible title

**Comment by chouseknecht** [comment]
Migrated to Jira: AAH-56
