### ISSUE TITLE
Importer: Lint execution environment file

### ISSUE THREAD

**Issue by bmclaughlin** [ansible/galaxy_ng#324]
If the execution environment metadata file is present at `meta/execution-environment.yml`, the file should be linted and any errors or warnings logged.

See section 1.3.2 of this [document](https://docs.google.com/document/d/1Lc8xMUrTlDVAxO0MFfHRCVORKlAXNGoBcj_r4UII8Qk/edit#) for definition details.

Subtask of #23

**Comment by newswangerd** [comment]
Moved to issues.redhat.com/
