### ISSUE TITLE
Story: Collection Deletion

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy_ng#329]
Enable an administrator to delete a Collection or a specific Collection Version through the API and UI. 

On c.rh.c we have been able to accomplish this on an ad-hoc basis using the Django Admin site, or through direct database access. As we migrate to the OSD 4 AppSRE platform these tools will not be available. This same issue will exist for standalone AH as well, so it's time to build a proper feature.

**Comment by newswangerd** [comment]
Moved to issues.redhat.com/
