### ISSUE TITLE
QE: Testing for upstream standalone Galaxy RPMs

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy_ng#335]
The Tower team is asking:

> What version of pulp installer should we use to install Hub? We have migrated to pulp 4.x installer and specify that it installs pulp 3.x since Hub requires 3.x pulp. We had to do this as a reaction to failing nightly installs. Is this the recommended way to install Hub? Should we continue to always use the latest pulp installer? Do we know which version of the installer we are going to be using at release time? At some point we will want to pin it to do our release verification.

From the Pulp team:

>The installer is version-locked with pulpcore, so each time there is a pulpcore release a new installer releases on galaxy.ansible.com as a collection https://galaxy.ansible.com/pulp/pulp_installer  If a new plugin got released, e.g. galaxy_ng then you can rerun the same version of the installer. Different plugins support different ranges of pulpcore, so that dictates what installers would work, also the installer receives various bugfixes and features so that plays into the choice also.

Tasks for QE:

- [ ] Put testing in place that tests upstream RPMs with the correct version of the installer, which according to the above, should be the released version that contains a puplcore dependency requirement matching our standalone pulpcore dependency requirement. I think our standalone dependency requirement is currently 3.4.1 [and can be found here]( https://github.com/ansible/galaxy_ng/blob/master/requirements/requirements.standalone.txt#L62)
- [ ] Upstream RPMs are here for now: http://koji.katello.org/releases/yum/katello-nightly/pulpcore/ We need to find out from Andrew Hills and team where the final upstream repos will live. 

Documentation Tasks (House):

- [ ] Make it clear in our end-user install instructions which version of the installer to use, and point toward installing via upstream RPMs.

**Comment by newswangerd** [comment]
Moved to issues.redhat.com/
