### ISSUE TITLE
Return 404 error when collection/version not found

### ISSUE THREAD

**Issue by jborean93** [ansible/galaxy_ng#341]
##### SUMMARY
When the collection does not exist and you are scanning for available versions the API response is not a 404 (Not Found) but rather an empty set of data results.

See https://github.com/ansible/ansible/issues/70940#issuecomment-665255558

##### STEPS TO REPRODUCE
Get request to `https://pulp/v3/collections/servicenow/fakenamespace/fakeversion/`

##### EXPECTED RESULTS
On Galaxy this returns a 404 and I would expect that to be the same for AH/Pulp/GalaxyNG.

##### ACTUAL RESULTS
Returns a 200 with the data:

```json
{
  "meta": {
    "count": 0
  },
  "links": {
    "first": "/api/v3/collections/servicenow/servicenow/versions/?limit=10&offset=0",
    "previous": null,
    "next": null,
    "last": "/api/v3/collections/servicenow/servicenow/versions/?limit=10&offset=0"
  },
  "data": []
}
```

**Comment by alikins** [comment]
@jborean93 

> https://pulp/v3/collections/servicenow/fakenamespace/fakeversion/

Seems like this URL should be `https://pulp/v3/collections/servicenow/fakenamespace/versions/fakeversion/` ? ie, the '/versions/' path segment seems to be missing.

**Comment by jborean93** [comment]
Yes sorry that is my bad.

**Comment by alikins** [comment]
closing for now.
