### ISSUE TITLE
ansible-lint not running on Automation Hub Imports

### ISSUE THREAD

**Issue by thedoubl3j** [ansible/galaxy_ng#363]
##### SUMMARY

Noticed in import logs that ansible-lint was encountering an exception and could not run over a few collections. I pulled down the collections locally and ansible-lint was able to run successfully over the collections.  

repos for 2 collections that could not run: 
https://github.com/IBM/ansible-for-i/tree/1.0.1
https://github.com/IBM/ansible-power-aix
##### STEPS TO REPRODUCE

1. upload collection to ah
2. review import logs

##### EXPECTED RESULTS

ansible-lint sucessfully runs
##### ACTUAL RESULTS

ansible-lint does not run

```
Getting doc strings via ansible-doc 
Finding content inside collection 
Loading role apply_all_loaded_ptfs 
Linting role apply_all_loaded_ptfs via ansible-lint... 
Exception running ansible-lint, could not complete linting 
Loading role check_ptf 
Linting role check_ptf via ansible-lint... 
Exception running ansible-lint, could not complete linting 
Loading role load_ptf 
Linting role load_ptf via ansible-lint... 
Exception running ansible-lint, could not complete linting 
```

**Comment by chouseknecht** [comment]
Migrated to Jira: AAH-51
