### ISSUE TITLE
UI: Imports from UI to use inbound-[namespace] url

### ISSUE THREAD

**Issue by awcrosby** [ansible/galaxy_ng#368]
Imports started from the UI should stop posting to the `automation-hub` url and repo, and instead use the `inbound-[namespace]` url and repo.

Related to #20

**Comment by newswangerd** [comment]
@awcrosby I believe this is already done

https://github.com/ansible/ansible-hub-ui/pull/163

Can you test it?

**Comment by chouseknecht** [comment]
Duplicate of #290
