### ISSUE TITLE
Pulp_ansible collection list only shows collection if highest version in repo

### ISSUE THREAD

**Issue by awcrosby** [ansible/galaxy_ng#411]
The `pulp_ansible` collection list only shows that a repo contains a collection if the highest version of the collection is in the repo. For example:

- `/pulp_ansible/galaxy/published/api/v3/collections/awcrosby/collection_test/versions/` shows many versions
- however `/pulp_ansible/galaxy/published/api/v3/collections/` does not show `collection_test` in list if the highest version is in another repo such as `staging`. This is likely related to the `is_highest` filter here: https://github.com/pulp/pulp_ansible/blob/master/pulp_ansible/app/galaxy/v3/views.py#L84 

This bug is also seen on `galaxy_ng` since we subclass that view: `/api/automation-hub/content/published/v3/collections/`

This does not seem to affect collection version, and therefore installing from a repo and getting the latest version works as expected.

https://pulp.plan.io/issues/7428

**Comment by fao89** [comment]
Ref: https://github.com/pulp/pulp_ansible/pull/360
