### ISSUE TITLE
Successful import response time long on AH

### ISSUE THREAD

**Issue by thedoubl3j** [ansible/galaxy_ng#412]
##### SUMMARY

The networking content team is reporting issues of failing import jobs when in fact the jobs are passing and the import is successful.
##### STEPS TO REPRODUCE

Kick off import job from zuul to AH. I will let @pabelanger and @cidrblock explain the gritty details.  

##### EXPECTED RESULTS

Endpoint posts a successful response
##### ACTUAL RESULTS

Job takes to long to respond with a success and corresponding CI job fails.

**Comment by pabelanger** [comment]
There looks to be a few things happening here.

1). up until 2 weeks ago, imports into AH seemed to happen in about 5mins.  As I understand it, there is 1 pod that is used to run ansible-test sanity.  And I believe the pod needs to be booted from scratch each time.  Now, it seems 15mins is not enough time for that ansible-test pod to go live.

2). After 15mins, it seems like the ansible-galaxy CLI client session expires, and the next poll from the CLI client gets 401, resulting in ansible-galaxy client returning an error.

https://c430eb1ec44eb981ef25-b7218c43e3d5ef0cc5d8df5ab3dca099.ssl.cf5.rackcdn.com/723b4bae03171884fcc55fb7b77dc11953a07f3f/release/release-ansible-collection-automation-hub/f162bb3/job-output.html#l945

Fix A, would be to update session timeout for API key, either bump highter then 15mins, or have ansible-galaxy CLI renew it.

Fix B, would be to see why AH now takes 15mins for CI to start running. One idea is to keep 1 pod online all the time, or debug startup issue.

**Comment by awcrosby** [comment]
The speed of import is due to infrastructure changes on OCPv4, there is rework being done to our backend jobs, and that is being addressed in: https://github.com/ansible/galaxy_ng/issues/342
