### ISSUE TITLE
Add 'distribution' to sync list data model

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy_ng#424]
In [PR #315](https://github.com/ansible/galaxy_ng/pull/315) we made the assumption that sync list name, repository name and distribution name will always be the same. That may not always be true. We may in the future allow users to create multiple sync lists and modify sync list names.

Future proof sync list by adding a field to the sync list data model that is a 1-to-1 foreign key to distribution model. This will create a reliable relationship between sync list and distribution, and avoid the potential for complex database migrations.

**Comment by chouseknecht** [comment]
Subtask of #17

**Comment by newswangerd** [comment]
Moved to issues.redhat.com/
