### ISSUE TITLE
Initiate curate task on collection move

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy_ng#428]
The task for [curating content](https://github.com/ansible/galaxy_ng/blob/master/galaxy_ng/app/tasks/synclist.py) needs to be initiated whenever a new collection lands in the golden repository.

The place where this task should be initiated has been identified here: 

https://github.com/ansible/galaxy_ng/blob/master/galaxy_ng/app/api/v3/viewsets/collection.py#L268

**Comment by chouseknecht** [comment]
https://gist.github.com/awcrosby/f412811feaca512c67586a12f9eefd3b

**Comment by chouseknecht** [comment]
Example implementation from @awcrosby: https://gist.github.com/awcrosby/f412811feaca512c67586a12f9eefd3b

**Comment by alikins** [comment]
@chouse @newswangerd And we want this on a /v3/ endpoint, not a /ui/ endpoint correct?

**Comment by alikins** [comment]
@chouse @newswangerd Assuming v3 endpoint, are there any additional RBAC requirements to account for?

For example, would it need to support letting user A move content to golden-repo, but not allow user A to trigger a curation of all the synclist repos? More importantly, does it need to do that _now_?. 

Can I assume that level of RBAC granularity isn't needed this sprint?

**Comment by chouseknecht** [comment]
I think based on the discussion in slack that we don't need to add RBAC to this. If a user has permission to invoke the move_content method, then they automatically have permission to invoke the curate task.

**Comment by alikins** [comment]
See also https://github.com/ansible/galaxy_ng/issues/285

**Comment by alikins** [comment]
One implementation is in https://github.com/ansible/galaxy_ng/pull/432

**Comment by hendersonreed** [comment]
What's the external representation of this task being kicked off? I see that in the response to the move-content response there's a `curate_task.id` returned. Is that going to be the primary way of determining that this task is running, or is there something else the tests should be evaluating as well?

**Comment by newswangerd** [comment]
Moved to issues.redhat.com/
