### ISSUE TITLE
Namespace deletion/rename option for admins

### ISSUE THREAD

**Issue by thedoubl3j** [ansible/galaxy_ng#429]
### Use Case

Allow for admins to delete namespaces in Automation Hub that do not contain artifacts. This came from an issues we ran into with a namespace being created for a partner and then that partner was acquired and needed to change the name of their namespace. 

It would be could for us to do this on the fly so that we don't have to request it from the galaxy team and pull them away from their current work. 
### Proposed Solution

Button to allow PE/Admins to delete a namespace with no collections. 
### Alternatives

Renaming could work here as well. Whichever path is easiest. 
### Implementation

Only thing I would do is add this into the namespace, rather stick it out in the open. Add as an option maybe in the edit namespace view.

**Comment by chouseknecht** [comment]
This was discussed in our planning meeting. Close for now. Will re-open in [Jira](https://issues.redhat.com) once it becomes part of a PRD.
