### ISSUE TITLE
RH Certified content sync count mismatch

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy_ng#438]
##### SUMMARY
After sync'ing content from c.rh.c -> local AH, the local collection count shows 55. The count on c.rh.c shows 53. Local hub seems to have 2 extra collections.

Here's what I see on c.rh.c: 

![53 collections](https://user-images.githubusercontent.com/1282865/93003601-1510ef00-f50e-11ea-9ed5-3baf35ef6c4a.png)

Here's what I see in local AH:

![55 collections](https://user-images.githubusercontent.com/1282865/93003545-a338a580-f50d-11ea-9f2b-4c2cd9f1471f.png)
 
The following is the local AH response from `/api/galaxy/_ui/v1/repo/rh-certified/?deprecated=false&offset=0&limit=12`

```
{
    "meta": {
        "count": 55
    },
    "links": {
        "first": "/api/galaxy/_ui/v1/repo/rh-certified/?deprecated=false&keywords=aws&limit=12&offset=0",
        "previous": null,
        "next": "/api/galaxy/_ui/v1/repo/rh-certified/?deprecated=false&keywords=aws&limit=12&offset=12",
        "last": "/api/galaxy/_ui/v1/repo/rh-certified/?deprecated=false&keywords=aws&limit=12&offset=43"
    },
   ...
```

The following is the local AH response from `/api/galaxy/content/rh-certified/v3/collections/`:

```
{
    "meta": {
        "count": 55
    },
    "links": {
        "first": "/api/galaxy/content/rh-certified/v3/collections/?limit=10&offset=0",
        "previous": null,
        "next": "/api/galaxy/content/rh-certified/v3/collections/?limit=10&offset=10",
        "last": "/api/galaxy/content/rh-certified/v3/collections/?limit=10&offset=45"
    },
    ...
```

##### STEPS TO REPRODUCE

1. Log into https://cloud.redhat.com/ansible/automation-hub/
2. View the collection count: 53
3. Copy token from c.rh.c -> red-hat-certified remote in local AH. 
4. Run sync on red-hat-certified

##### EXPECTED RESULTS
I would expect the counts to match.

##### ACTUAL RESULTS
According to the count, there are 2 extra collections in local AH.

**Comment by newswangerd** [comment]
This is happening because pulp_ansible isn't saving the collection's deprecation status during sync. The extra two collections that show up in the sync are deprecated on cloud.redhat.com

**Comment by newswangerd** [comment]
Pulp issue: https://pulp.plan.io/issues/7504

**Comment by fao89** [comment]
Ref: https://github.com/pulp/pulp_ansible/pull/358

**Comment by newswangerd** [comment]
Moved to issues.redhat.com/
