### ISSUE TITLE
Documentation missing for RH Certified collections

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy_ng#441]
##### SUMMARY
After sync'ing collections from c.rh.c -> local AH, collection documentation is missing for all collections. Tested with galaxy-ng 4.2.0b2 installed via pip.

##### STEPS TO REPRODUCE

1. Sync collections from c.rh.c -> local AH
2. In local AH, set the content selector to Red Hat Certified 
3. Click on a collection.

##### EXPECTED RESULTS
Expecting to see all of the collection documentation that's visible on c.rh.c. 

##### ACTUAL RESULTS
Documentation is not rendered:

![Missing Docs](https://user-images.githubusercontent.com/1282865/93004130-2c51db80-f512-11ea-9ce2-44cb4f4d923f.png)

https://pulp.plan.io/issues/7551

**Comment by chouseknecht** [comment]
We've added a docs blob endpoint that needs to be pushed to Prod c.rh.c. This endpoint is currently in CI.

**Comment by chouseknecht** [comment]
@rochacbruno will test the sync process from c.rh.c CI -> local AH.

**Comment by alikins** [comment]
some version info:
pulp 3.6.0
pulp_ansible 0.3.0  ?

galaxy_ng from pypi?

**Comment by chouseknecht** [comment]
Looks like @fao89 found a fix: https://github.com/pulp/pulp_ansible/pull/375

**Comment by newswangerd** [comment]
Moved to issues.redhat.com/
