### ISSUE TITLE
UXD: Can't find URL for configuring ansible-galaxy CLI

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy_ng#456]
##### SUMMARY
The URL field for each repository listed on the Repo Management page contains a value that is not compatible with the `ansible-galaxy` CLI. It is however compatible with the `pulp_ansible` sync tool, so it can be used to sync from one installation of AH to another. 

Perhaps the Repo Management page is the wrong place to look for a URL for configuring the CLI to publish/install collections, but it's the only place where one can find a URL for a given repository.

##### STEPS TO REPRODUCE
1. Go to Repo Management page. 
2. Click the copy button next to the URL field for one of the listed repositories.
3. Paste the URL into `ansible.cfg` 
4. Attempt to install a collection from the server

Example `ansible.cfg` file:

```
[galaxy]
server_list=cloud

[galaxy_server.cloud]
url=https://<server>/api/galaxy/content/published/v3/collections
token=<token-value-here>
```

##### EXPECTED RESULTS
I should be able to paste the URL value directly into an `ansible.cfg` file as a server.url value, and immediately download and install collections.

##### ACTUAL RESULTS

The `ansible-galaxy` CLI returns the following:

```
ERROR! Tried to find galaxy API root at https://<server>/api/galaxy/content/published/v3/collections but no 'available_versions' are available on https://<server>/api/galaxy/content/published/v3/collections
```

If you remove `/v3/collections` from the end of the URL (the value copied from AH), it works. I would expect the URL copied from the UI to just work. It's not documented anywhere that I would need to modify it prior to using it with the CLI.

**Comment by chouseknecht** [comment]
Turns our for publishing collections one can get the URL of the inbound repo by navigating to My Namespaces, clicking on a card, and selecting the `CLI Configuration` tab. 

Perhaps we need something similar on the Collections Detail page, helping a user who wants to install the selected collection.

**Comment by alikins** [comment]
`https://<server>/api/galaxy/content/published/`  should be the right url for ansible.cfg as mentioned.

Easiest "fix" may be to include a "ansible-galaxy config" URL and a "automation-hub remote sync URL" in the UI.  Not very elegant, but maybe okay for now.

**Comment by hendersonreed** [comment]
Closing, this is resolved.
