### ISSUE TITLE
Publish collection checksum on Galaxy

### ISSUE THREAD

**Issue by ddimatos** [ansible/galaxy_ng#461]
## Feature Request
Today, collection archives have metadata (FILES.json) that have the checksum for each file included in the archive, it would be helpful for our users who download a collection tarball be provided the cheksum to validate the downloaded archive integrity. 

The FILES.json is used during the install by `ansible-galaxy collection install -f *.tar.gz` but that only tells the user post download and during installation their archive is corrupt. The cryptic message (to some) could be avoided if they were instructed to check validity of the the download. 

ie
```
ERROR! Checksum mismatch for 'plugins/modules/foo.py' inside collection at '/apps/ansible/org-foo-1.0.tar.gz'
```
### Use Case
This issue resolves the use case where a tarball is downloaded from Galaxy such that the integrity of the download is not corrupt. 

### Proposed Solution
I would like that the checksum be properly displayed in the collections landing page. 

### Implementation
Suggested approach:
<img width="844" alt="image" src="https://user-images.githubusercontent.com/25803172/93411223-8377e900-f84f-11ea-8444-226bd46f5794.png">

**Comment by chouseknecht** [comment]
This info is already available in the API, and should be used by the `ansible-galaxy` client:

Here's the API endpoint:

```
https://<server>/api/<galaxy>/v3/collections/<namespace>/<collection>/versions/<version_number>/
```

The response object looks like the following:

```
{
    "version": "1.0.2",
    "certification": "certified",
    "href": "/api/automation-hub/v3/collections/tirasa/syncope/versions/1.0.2/",
    "created_at": "2019-11-18T16:15:43.541018Z",
    "updated_at": "2019-11-18T16:15:43.541051Z",
    "artifact": {
        "filename": "tirasa-syncope-1.0.2.tar.gz",
        "sha256": "1270b3949a5ce0cae2e0ce27162cc5a3989a0b4b01050d2f3543c3172e5cc28e",
        "size": 250419
    },
    "collection": {
        "id": "1d1d119c-cfed-4ed5-8d33-94371a4905b6",
        "name": "syncope",
        "href": "/api/automation-hub/v3/collections/tirasa/syncope/"
    },
    "download_url": "https://cloud.redhat.com/api/automation-hub/v3/artifacts/collections/automation-hub/tirasa-syncope-1.0.2.tar.gz",
    "name": "syncope",
    "namespace": {
        "name": "tirasa"
    },
    "metadata": {
        "authors": [
            "Matteo Alessandroni",
            "Federico Palmitesta",
            "Marco Di Sabatino Di Diodoro",
            "Francesco Chicchiriccò"
        ],
        "contents": [
            {
                "name": "syncope_user_handler",
                "description": "Handle user on Apache Syncope",
                "content_type": "module"
            }
        ],
        "dependencies": {},
        "description": "",
        "documentation": "",
        "homepage": "https://github.com/Tirasa/SyncopeAnsible",
        "issues": "https://github.com/Tirasa/SyncopeAnsible/issues",
        "license": [
            "Apache-2.0"
        ],
        "repository": "https://github.com/Tirasa/SyncopeAnsible",
        "tags": [
            "security",
            "syncope",
            "tools",
            "application"
        ]
    }
}
```

**Comment by chouseknecht** [comment]
And.. I think the `ansible-galaxy` client is already checking the hash here: https://github.com/ansible/ansible/blob/devel/lib/ansible/galaxy/collection.py#L1398

**Comment by ddimatos** [comment]
Thanks @chouseknecht - took me some time to get back to this, exactly the answer I was looking for.
`https://galaxy.ansible.com/api/v2/collections/ibm/ibm_zos_core/versions/1.3.0-beta.1/`
