### ISSUE TITLE
Flexible Pulp client configuration

### ISSUE THREAD

**Issue by Spredzy** [ansible/galaxy_ng#464]
Enable the following configuration options on the Pulp client:

- define the protocol to used to talk to the pulp backend server. (ie. `http` or `https`)
- disable TLS certificate validation

The above options will help with the integration of AH into Tower development and CI.

**Comment by chouseknecht** [comment]
@cutwater please review the associated PRs

**Comment by Spredzy** [comment]
The mentionned PRs have been merged.
