### ISSUE TITLE
UI: Disable groups and repo management in navigation for users with no permissions

### ISSUE THREAD

**Issue by newswangerd** [ansible/galaxy_ng#467]
Disable groups and and repo management in the navigation menu for users that don't have permissions to view these pages.

Additionally, controls for creating, editing and deleting groups as well as the button for syncing and editing remotes should be disabled based on the users permissions.

![Screen Shot 2020-09-17 at 2 42 13 PM](https://user-images.githubusercontent.com/6063371/93513611-18ccb900-f8f4-11ea-8fe0-619a3dbf16ec.png)

**Comment by chouseknecht** [comment]
blocked by #468

**Comment by newswangerd** [comment]
Moved to issues.redhat.com/
