### ISSUE TITLE
Surface extra permissions to the API

### ISSUE THREAD

**Issue by newswangerd** [ansible/galaxy_ng#468]
Add the APIs to support #467

**Comment by rochacbruno** [comment]
@newswangerd do you have more  details about the requirements for this issue?

Which endpoints and which data it is supposed to expose?

tks

**Comment by newswangerd** [comment]
We need to surface permissions for groups and remotes here: https://github.com/ansible/galaxy_ng/blob/master/galaxy_ng/app/api/ui/serializers/user.py#L111

I think surfacing add, change, view and delete for groups, remotes and distributions should do the trick.
