### ISSUE TITLE
UI: Add about modal and help dropdown

### ISSUE THREAD

**Issue by newswangerd** [ansible/galaxy_ng#469]
We need to add a help dropdown and about modal with documentation and links for customer support. The about modal will contain information that users can send to customer support such as the version of the app that is being used.

For now we will just copy the same layout that cloud.redhat.com uses.

![Screen Shot 2020-09-17 at 2 47 49 PM](https://user-images.githubusercontent.com/6063371/93514692-83cabf80-f8f5-11ea-9d97-9ccfbcf82f1d.png)
![Screen Shot 2020-09-17 at 2 48 04 PM](https://user-images.githubusercontent.com/6063371/93514694-83cabf80-f8f5-11ea-9302-d17a6ad57523.png)

**Comment by ZitaNemeckova** [comment]
Depends on #470

**Comment by newswangerd** [comment]
Moved to issues.redhat.com/
