### ISSUE TITLE
Remove instances where we still proxy api requests to pulp

### ISSUE THREAD

**Issue by newswangerd** [ansible/galaxy_ng#472]
There are still a couple of views that use the old pulp_ansible client to proxy requests to pulp_ansible. These should be replaced with subclassed viewsets sometime before GA.

**Comment by alikins** [comment]
A few notes:

The two places where galaxy_pulp is used are:
- api/ui/viewsets/tags.py  - Based on discussion with @newswangerd it seems like this interface is no longer used
- api/ui/viewsets/collection.py -  This is primary user of galaxy_pulp.

The collection.py viewsets that use galaxy_pulp are:
- CollectionViewSet
- CollectionViewSetDeprecated
- CollectionVersionViewSet
- CollectionImportViewSet

The CollectionRemoteViewSet does not use galaxy_pulp

The main diffs between these _ui viewsets and the v3 style viewsets are:
- various custom filters and query params
- different output serializers

**Comment by alikins** [comment]
The next steps are:

- replace collection.py Viewsets with db based views

Then remove galaxy_pulp infrastructure

**Comment by newswangerd** [comment]
Moved to issues.redhat.com/
