### ISSUE TITLE
Disable pulp APIs

### ISSUE THREAD

**Issue by newswangerd** [ansible/galaxy_ng#473]
Pulp's APIs don't respect our RBAC rules and occasionally surface information that should be kept secret (such as cloud.redhat.com tokens).

We need to identify which URLs we want to disable from the pulp API and override them using webserver snippets.

The ability to override webserver snippets is being added to the pulp installer now: https://pulp.plan.io/issues/7471

galaxy_ng still relies on some of the pulp APIs, so extra care needs to be taken to not disable APIs we rely on until #472 has been fixed.

Example configs:  https://pulp.plan.io/issues/7471#note-3

Note: we need to ship apache and nginx configs

**Comment by hendersonreed** [comment]
Closing, this is/was tracked in Jira.
