### ISSUE TITLE
FIPS compliance settings

### ISSUE THREAD

**Issue by newswangerd** [ansible/galaxy_ng#474]
There's a new setting in pulp 3.7.0 that allows users to set a list of allowed checksums: https://github.com/pulp/pulpcore/blob/master/docs/settings.rst#allowed_content_checksums

To be FIPS compliant we need to set the allowed checksums to

```
{"sha224", "sha256", "sha384", "sha512"}
```

and test galaxy_ng on a FIPS compliant os to ensure that it works.

**Comment by chouseknecht** [comment]
Need pulp 3.7.0 release and a release of pulp_ansible that supports 3.7.0

**Comment by bmbouter** [comment]
For pulpcore 3.7.0 FIPS environments, I recommend configuring the [ALLOWED_CONTENT_CHECKSUMS](https://docs.pulpproject.org/pulpcore/en/3.7/settings.html#allowed-content-checksums) setting with these values:

`ALLOWED_CONTENT_CHECKSUMS = ["sha224", "sha256", "sha384", "sha512"]`

If you use the pulp_ansible installer version 3.7.0 it will also ensure all of your dependencies are also FIPS compatible at install time. For rpm builds, we've sent over the only necessary patch (for Django) to the build team building your RPMs here: https://github.com/theforeman/pulpcore-packaging/pull/21/files

For an environment to test FIPS in, pulplift provides both an EL7-fips and EL8-fips environments. If you want to enable it in another environment, e.g. EL7 [here are some docs](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/security_guide/chap-federal_standards_and_regulations) on how to use the kernel param.

**Comment by daviddavis** [comment]
@bmbouter I had the thought yesterday that galaxy_ng could just always set `ALLOWED_CONTENT_CHECKSUMS = ["sha224", "sha256", "sha384", "sha512"]` regardless of whether it's in FIPS mode or not. Would that work?

**Comment by bmbouter** [comment]
> @bmbouter I had the thought yesterday that galaxy_ng could just always set `ALLOWED_CONTENT_CHECKSUMS = ["sha224", "sha256", "sha384", "sha512"]` regardless of whether it's in FIPS mode or not. Would that work?

Yes I believe this setting would be safe to apply in all environments.

**Comment by newswangerd** [comment]
Moved to issues.redhat.com/
