### ISSUE TITLE
Community remote configuration fail

### ISSUE THREAD

**Issue by ironfroggy** [ansible/galaxy_ng#475]
##### SUMMARY
Syncing from community remote fails both in executing the sync or in editing its settings.

##### STEPS TO REPRODUCE
- Navigate to the Remotes list
- Attempt to edit the Community remote configuration
- Attempt to save without making any changes
- Cancel and then try to sync the Community remote

##### EXPECTED RESULTS
- To be able to customize the configuration of the Community remote 
- To be able to sync collections from Community Galaxy

##### ACTUAL RESULTS

When editing:
`Invalid URL https://galaxy.ansible.com/api/v2/collections. Ensure the URL ends in either '/v2/collections' or '/v3/collections'`

When running:
`Expecting value: line 1 column 1 (char 0)`

**Comment by alikins** [comment]
I've been noticing some oddness in the ui for remotes. Sometimes the 'requirements.yml' disappears after it's been set. Maybe related?

**Comment by alikins** [comment]
Seems related (secondary?) to https://github.com/ansible/galaxy_ng/issues/456 
(urls differences between ansible-galaxy config and pulp remotes and only the latter is shown in the ui)?
