### ISSUE TITLE
Upgrade to Pulp 3.7.0

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy_ng#476]
- Upgrade to pulpcore 3.7.0 and allow for 3.8.0 (see https://docs.pulpproject.org/pulpcore/restapi.html#tag/Status)
- Upgrade pulp_container to compatibility release for pulpcore 3.7.0
- Upgrade pulp_ansible to compatibility release for pulpcore 3.7.0
- Regenerate Travis CI template after the above are completed

**Comment by newswangerd** [comment]
Related: https://github.com/ansible/galaxy_ng/issues/474

**Comment by alikins** [comment]
Pulp api status docs: 
https://docs.pulpproject.org/pulpcore/plugins/plugin-writer/concepts/index.html#plugin-api-stability-and-deprecation-policy
(source https://github.com/pulp/pulpcore/blob/master/docs/plugins/plugin-writer/concepts/index.rst#plugin-api-stability-and-deprecation-policy)

**Comment by chouseknecht** [comment]
@alikins 

From the #pulp-dev irc channel:  pulpcore 3.7.0, pulp_ansible 0.4.0 and pulp_container

**Comment by bmbouter** [comment]
pulp_container compatibility version will be 2.1.0

**Comment by alikins** [comment]
Fix committed via pr #483

**Comment by bmbouter** [comment]
pulpcore 3.7.0, pulp_ansible 0.4.0 and pulp_container 2.1.0 are all available on pypi

**Comment by bpereto** [comment]
pulpcore 3.9.0 is out.

**Comment by newswangerd** [comment]
Moved to issues.redhat.com/
