### ISSUE TITLE
New user creation shows "in a few seconds" instead of "a few seconds ago"

### ISSUE THREAD

**Issue by anshulbehl** [ansible/galaxy_ng#479]
##### SUMMARY

New user creation in Automation Hub says "in a few seconds" instead of "a few seconds ago"
Please check the screenshot attached
##### ACTUAL RESULTS

```

```
![image](https://user-images.githubusercontent.com/6129262/93910032-292eca80-fd1e-11ea-8828-667cb2025486.png)

**Comment by newswangerd** [comment]
Huh. This is an interesting bug. @anshulbehl is the time on your computer set correctly?

**Comment by newswangerd** [comment]
Moved to issues.redhat.com/
