### ISSUE TITLE
Importer: Limit on author field in galaxy.yml inside collection

### ISSUE THREAD

**Issue by anshulbehl** [ansible/galaxy_ng#482]
##### SUMMARY

A partner is facing below issue uploading their collection to AH
```
 {'authors': {1: [ErrorDetail(string='Ensure this field has no more than 64 characters.', code='max_length')]}}
```
##### STEPS TO REPRODUCE

galaxy.yml present here: https://github.com/CiscoDevNet/ansible-mso/blob/master/galaxy.yml

##### EXPECTED RESULTS

Collection should be uploaded
##### ACTUAL RESULTS

Partner is getting error while uploading the collection

```
 {'authors': {1: [ErrorDetail(string='Ensure this field has no more than 64 characters.', code='max_length')]}}
```

**Comment by awcrosby** [comment]
This is the current storage length in the database, the check was added recently in pulp. This same check needs to be added in `galaxy-importer` so it fails earlier than at the end of an upload, this was added as a task to this issue: https://github.com/ansible/galaxy_ng/issues/162

**Comment by anshulbehl** [comment]
@awcrosby @abenokraitis This is blocking the upload of `cisco.mso` collection v1.0.0 to Automation Hub

**Comment by gundalow** [comment]
Does anything require the email addresses:
```yaml
authors:
- Dag Wieers (@dagwieers) <dag@wieers.com>
- Nirav Katarmal (@nkatarmal-crest) <nirav.katarmal@crestdatasys.com>
- Lionel Hercot (@lhercot) <lhercot@cisco.com>
- Cindy Zhao (@cizhao) <cizhao@cisco.com>
- Shreyas Srish (@shrsr) <ssrish@cisco.com>
```

Or could that be simplified to `Nirav Katarmal (@nkatarmal-crest)`

**Comment by newswangerd** [comment]
Moved to issues.redhat.com/
