### ISSUE TITLE
Cloud user has multiple synclists in /repositories

### ISSUE THREAD

**Issue by awcrosby** [ansible/galaxy_ng#492]
In CI the `ansible-insights` user has 3 synclist repos (`1460290-synclist` `6089719-synclist` `6269497-synclist`) listed under https://ci.cloud.redhat.com/beta/ansible/automation-hub/repositories/ when there should only be one.

This is the possible cause of the following errors: 
- The UI "sync" toggle is not showing for the ansible-insights user on collections page
- With the `ansible-insights` user having all synclist permissions, a 403 `permission_denied` occurs at https://ci.cloud.redhat.com/api/automation-hub/_ui/v1/my-synclists/

**Comment by alikins** [comment]
@awcrosby Which groups / accounts does the ansible-insights user live in CI?

This may be totally unrelated, but I'm kind of wondering if the multiple synclists are an artifact from my testing against CI (often with semi-kluged auth credentials that includes the account number ( group number)). I guess there aren't a lot of other CI users with synclists to compare it to.

**Comment by alikins** [comment]
> https://ci.cloud.redhat.com/api/automation-hub/_ui/v1/my-synclists/

My first wild guess would be that there isn't a  guardian_groupobjectpermission instance for those synclists. Possibly as result of being created before the  synclist code did the RBAC assignments correctly.  

Though, for that matter, it may well be that synclists don't get created with all the proper perms.

**Comment by newswangerd** [comment]
Moved to issues.redhat.com/
