### ISSUE TITLE
Repositories created by inbound namespace migration are missing associated data

### ISSUE THREAD

**Issue by awcrosby** [ansible/galaxy_ng#493]
The `Repository` initial `RepositoryVersion` was not created by [0003_inbound_repo_per_namespace](https://github.com/ansible/galaxy_ng/blob/master/galaxy_ng/app/migrations/0003_inbound_repo_per_namespace.py), since the `Repository.save()` method is overridden with extra logic and migrations do not apply model methods.

As seen in CI environment this prevents import to the repo as it references repo.latest().

A new migration will be needed with necessary model method logic brought over into the migration, to re-create or update these repositories and distributions.

**Comment by alikins** [comment]
Notes to myself for the future:

> since the Repository.save() method is overridden with extra logic and migrations do not apply model methods.

The Repository.save() in question:
https://github.com/pulp/pulpcore/blob/master/pulpcore/app/models/repository.py#L57-L69

The django fine print on why it is skipped:
https://docs.djangoproject.com/en/3.1/topics/migrations/#historical-models

in particular:

> This means that you will NOT have custom save() methods called on objects when you access them in migrations, and you will NOT have any custom constructors or instance methods. Plan appropriately!

Other interesting note I hadn't thought about:

> In addition, the concrete base classes of the model are stored as pointers, so you must always keep base classes around for as long as there is a migration that contains a reference to them. On the plus side, methods and managers from these base classes inherit normally, so if you absolutely need access to these you can opt to move them into a superclass.

**Comment by newswangerd** [comment]
Moved to issues.redhat.com/
