### ISSUE TITLE
Verify deprecated attribute gets handled correctly in sync list repos

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy_ng#498]
See the pulp_ansible change here: https://github.com/pulp/pulp_ansible/pull/366/files 

The deprecated attribute for a collection_version is being scoped to a repository, rather than globally. This means the deprecated attribute should be copied from the golden repo to the sync list repo.

**Comment by chouseknecht** [comment]
@fao89 will expand the pulp_ansible PR (above) to make sure the copy operation includes the deprecated attribute

**Comment by newswangerd** [comment]
Moved to issues.redhat.com/
