### ISSUE TITLE
UI: present sample ansible.cfg for publishing

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy_ng#499]
Content creators need to know how to configure `ansible-galaxy` when publishing a collection. 

We were originally thinking that artifacts would be published to distribution specific endpoints. However, we also decided to provide backward compatible support for the default publish endpoint, making it smart enough to inspect an inbound artifact and place it in the correct repository.

Work with the Product and UXD teams to determine the correct publish URL to present to the user, and the best way to instruct the user on how to configure the `ansible-galaxy` client.

**Comment by newswangerd** [comment]
Moved to issues.redhat.com/
