### ISSUE TITLE
Collections list in v3 showing wrong count in CI env

### ISSUE THREAD

**Issue by awcrosby** [ansible/galaxy_ng#508]
`staging` repo has 0 collections, correctly show in ui collection list: 
https://ci.cloud.redhat.com/api/automation-hub/_ui/v1/repo/staging/
But v3 collections list shows count as 5289 (there are only ~4800 collections in CI): https://ci.cloud.redhat.com/api/automation-hub/content/staging/v3/collections/

`published` repo has 4803 collections, correctly shown in ui collection list: https://ci.cloud.redhat.com/api/automation-hub/_ui/v1/repo/published/ 
But v3 collections list does a 504 timeout: https://ci.cloud.redhat.com/api/automation-hub/content/published/v3/collections/ 

Repos with smaller numbers of collections seem ok: https://ci.cloud.redhat.com/api/automation-hub/content/synctest/v3/collections/

**Comment by awcrosby** [comment]
Empty repo showing wrong data was resolved by https://github.com/pulp/pulp_ansible/pull/384

The 504 is caused by a separate issue, https://pulp.plan.io/issues/7564

**Comment by newswangerd** [comment]
Moved to issues.redhat.com/
