### ISSUE TITLE
Include UI in Pulp installer

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy_ng#61]
Subtask of #51 

Include Automation Hub UI in the installer. 

- [x] Add UI to the production deployment so that installing the galaxy_ng Python package includes a pre-built UI package.
- ~~[ ] Add support for development mode (i.e., source install) such that a user can do galaxy_ng UI development~~

**Comment by alikins** [comment]
(sounds right-ish to me)

**Comment by fabricio-aguiar** [comment]
Related PR: https://github.com/ansible/galaxy_ng/pull/66
Role for UI: https://github.com/fabricio-aguiar/galaxy_ng_prerequisites
