### ISSUE TITLE
TASK [pulp-database : Run database auth migrations] in playbook install.yml fails.

### ISSUE THREAD

**Issue by denysdomin** [ansible/galaxy_ng#91]
TASK [pulp-database : Run database auth migrations] fails when running playbook install.yml

TASK [pulp-database : Run database auth migrations] ******************************************************************************************************************************
fatal: [35.178.172.220]: FAILED! => {"changed": true, "cmd": ["/usr/local/lib/pulp/bin/django-admin", "migrate", "auth", "--no-input"], "delta": "0:00:00.658146", "end": "2020-04-19 11:08:35.107148", "msg": "non-zero return code", "rc": 1, "start": "2020-04-19 11:08:34.449002", "stderr": "Traceback (most recent call last):\n  File \"/usr/local/lib/pulp/bin/django-admin\", line 8, in <module>\n    sys.exit(execute_from_command_line())\n  File \"/usr/local/lib/pulp/lib/python3.6/site-packages/django/core/management/__init__.py\", line 381, in execute_from_command_line\n    utility.execute()\n  File \"/usr/local/lib/pulp/lib/python3.6/site-packages/django/core/management/__init__.py\", line 325, in execute\n    settings.INSTALLED_APPS\n  File \"/usr/local/lib/pulp/lib/python3.6/site-packages/django/conf/__init__.py\", line 79, in __getattr__\n    self._setup(name)\n  File \"/usr/local/lib/pulp/lib/python3.6/site-packages/django/conf/__init__.py\", line 66, in _setup\n    self._wrapped = Settings(settings_module)\n  File \"/usr/local/lib/pulp/lib/python3.6/site-packages/django/conf/__init__.py\", line 157, in __init__\n    mod = importlib.import_module(self.SETTINGS_MODULE)\n  File \"/usr/lib/python3.6/importlib/__init__.py\", line 126, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n  File \"<frozen importlib._bootstrap>\", line 994, in _gcd_import\n  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n  File \"<frozen importlib._bootstrap>\", line 955, in _find_and_load_unlocked\n  File \"<frozen importlib._bootstrap>\", line 665, in _load_unlocked\n  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"/usr/local/lib/pulp/src/pulpcore/pulpcore/app/settings.py\", line 73, in <module>\n    plugin_app_config = entry_point.load()\n  File \"/usr/local/lib/pulp/lib/python3.6/site-packages/pkg_resources/__init__.py\", line 2449, in load\n    self.require(*args, **kwargs)\n  File \"/usr/local/lib/pulp/lib/python3.6/site-packages/pkg_resources/__init__.py\", line 2472, in require\n    items = working_set.resolve(reqs, env, installer, extras=self.extras)\n  File \"/usr/local/lib/pulp/lib/python3.6/site-packages/pkg_resources/__init__.py\", line 792, in resolve\n    raise VersionConflict(dist, req).with_context(dependent_req)\npkg_resources.VersionConflict: (pulpcore 3.4.0.dev0 (/usr/local/lib/pulp/src/pulpcore), Requirement.parse('pulpcore<3.3,>=3.0'))", "stderr_lines": ["Traceback (most recent call last):", "  File \"/usr/local/lib/pulp/bin/django-admin\", line 8, in <module>", "    sys.exit(execute_from_command_line())", "  File \"/usr/local/lib/pulp/lib/python3.6/site-packages/django/core/management/__init__.py\", line 381, in execute_from_command_line", "    utility.execute()", "  File \"/usr/local/lib/pulp/lib/python3.6/site-packages/django/core/management/__init__.py\", line 325, in execute", "    settings.INSTALLED_APPS", "  File \"/usr/local/lib/pulp/lib/python3.6/site-packages/django/conf/__init__.py\", line 79, in __getattr__", "    self._setup(name)", "  File \"/usr/local/lib/pulp/lib/python3.6/site-packages/django/conf/__init__.py\", line 66, in _setup", "    self._wrapped = Settings(settings_module)", "  File \"/usr/local/lib/pulp/lib/python3.6/site-packages/django/conf/__init__.py\", line 157, in __init__", "    mod = importlib.import_module(self.SETTINGS_MODULE)", "  File \"/usr/lib/python3.6/importlib/__init__.py\", line 126, in import_module", "    return _bootstrap._gcd_import(name[level:], package, level)", "  File \"<frozen importlib._bootstrap>\", line 994, in _gcd_import", "  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load", "  File \"<frozen importlib._bootstrap>\", line 955, in _find_and_load_unlocked", "  File \"<frozen importlib._bootstrap>\", line 665, in _load_unlocked", "  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module", "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed", "  File \"/usr/local/lib/pulp/src/pulpcore/pulpcore/app/settings.py\", line 73, in <module>", "    plugin_app_config = entry_point.load()", "  File \"/usr/local/lib/pulp/lib/python3.6/site-packages/pkg_resources/__init__.py\", line 2449, in load", "    self.require(*args, **kwargs)", "  File \"/usr/local/lib/pulp/lib/python3.6/site-packages/pkg_resources/__init__.py\", line 2472, in require", "    items = working_set.resolve(reqs, env, installer, extras=self.extras)", "  File \"/usr/local/lib/pulp/lib/python3.6/site-packages/pkg_resources/__init__.py\", line 792, in resolve", "    raise VersionConflict(dist, req).with_context(dependent_req)", "pkg_resources.VersionConflict: (pulpcore 3.4.0.dev0 (/usr/local/lib/pulp/src/pulpcore), Requirement.parse('pulpcore<3.3,>=3.0'))"], "stdout": "", "stdout_lines": []}

**Comment by denysdomin** [comment]
I've tried on Centos 7 and Ubuntu 18.06. In AWS.

**Comment by chouseknecht** [comment]
Ran into the same issue with Centos 8.1. The fix for now is to pin pulpcore using the following in your playbook, under the `vars` section:

```
...
    pulp_source_dir: "git+https://github.com/pulp/pulpcore.git@3.3.0#egg=pulpcore"
```

**Comment by chouseknecht** [comment]
Running with the latest instructions in the README, this is now working.
